# Generated by Django 6.1.1 on 2026-09-11 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('vouchers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Mã đơn hàng')),
                ('is_guest', models.BooleanField(db_index=True, default=False, verbose_name='Mua không cần đăng nhập (Khách vãng lai)')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Họ tên người nhận')),
                ('customer_phone', models.CharField(db_index=True, max_length=20, verbose_name='Số điện thoại')),
                ('customer_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email nhận thông báo')),
                ('delivery_address', models.CharField(max_length=255, verbose_name='Địa chỉ chi tiết')),
                ('delivery_city', models.CharField(default='Hà Nội', max_length=100, verbose_name='Tỉnh/Thành phố')),
                ('delivery_district', models.CharField(default='Cầu Giấy', max_length=100, verbose_name='Quận/Huyện')),
                ('delivery_ward', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phường/Xã')),
                ('delivery_note', models.TextField(blank=True, null=True, verbose_name='Ghi chú giao hàng')),
                ('payment_method', models.CharField(choices=[('COD', 'Thanh toán khi nhận hàng (COD)'), ('VNPAY', 'Cổng thanh toán VNPay Sandbox (ATM / QR / Thẻ)'), ('BANKING', 'Chuyển khoản ngân hàng VietQR'), ('WALLET', 'Ví điểm EcoPay')], default='COD', max_length=20, verbose_name='Phương thức thanh toán')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Chờ thanh toán'), ('PAID', 'Đã thanh toán'), ('FAILED', 'Thanh toán thất bại'), ('REFUNDED', 'Đã hoàn tiền')], db_index=True, default='PENDING', max_length=20, verbose_name='Trạng thái thanh toán')),
                ('order_status', models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('PROCESSING', 'Đang đóng gói'), ('SHIPPING', 'Đang giao hàng'), ('COMPLETED', 'Giao hàng thành công'), ('CANCELLED', 'Đã hủy đơn')], db_index=True, default='PENDING', max_length=20, verbose_name='Trạng thái đơn hàng')),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Tiền hàng (VNĐ)')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Số tiền giảm giá (VNĐ)')),
                ('shipping_fee', models.DecimalField(decimal_places=0, default=20000, max_digits=12, verbose_name='Phí vận chuyển (VNĐ)')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Tổng thanh toán cuối cùng (VNĐ)')),
                ('voucher_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã voucher snapshot')),
                ('loyalty_points_used', models.PositiveIntegerField(default=0, verbose_name='Điểm thưởng đã cấn trừ')),
                ('loyalty_points_earned', models.PositiveIntegerField(default=0, verbose_name='Điểm thưởng tích lũy được')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP người đặt')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='Trình duyệt / Thiết bị')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng thành viên')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='vouchers.voucher', verbose_name='Mã giảm giá đã dùng')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Danh sách Đơn hàng',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=255, verbose_name='Tên sản phẩm tại thời điểm mua')),
                ('product_sku', models.CharField(max_length=50, verbose_name='Mã SKU')),
                ('product_image', models.CharField(max_length=500, verbose_name='Ảnh sản phẩm')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Đơn giá (VNĐ)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Thành tiền (VNĐ)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Đơn hàng')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn hàng',
                'verbose_name_plural': 'Danh sách Chi tiết đơn hàng',
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Trạng thái trước')),
                ('new_status', models.CharField(max_length=50, verbose_name='Trạng thái mới')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghi chú')),
                ('created_by', models.CharField(default='SYSTEM', max_length=100, verbose_name='Người cập nhật')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='orders.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Lịch sử trạng thái đơn',
                'verbose_name_plural': 'Lịch sử trạng thái đơn',
                'db_table': 'order_status_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
