# Generated by Django 6.1.1 on 2026-09-11 03:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Mã voucher')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề chương trình')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả chi tiết')),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Phần trăm (%)'), ('FIXED', 'Số tiền cố định (VNĐ)')], default='PERCENT', max_length=20, verbose_name='Loại giảm giá')),
                ('discount_value', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá trị giảm (% hoặc VNĐ)')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Giảm tối đa (VNĐ)')),
                ('min_order_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Đơn hàng tối thiểu (VNĐ)')),
                ('usage_limit', models.PositiveIntegerField(default=1000, verbose_name='Giới hạn số lần dùng')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Số lần đã dùng')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateTimeField(verbose_name='Ngày kết thúc')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Đang kích hoạt')),
            ],
            options={
                'verbose_name': 'Mã giảm giá',
                'verbose_name_plural': 'Danh sách Mã giảm giá',
                'db_table': 'vouchers',
                'ordering': ['-created_at'],
            },
        ),
    ]
