# Generated by Django 6.1.1 on 2026-09-11 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer_name', models.CharField(max_length=255, verbose_name='Tên người đánh giá')),
                ('rating', models.IntegerField(default=5, verbose_name='Số sao đánh giá (1-5)')),
                ('comment', models.TextField(verbose_name='Nội dung nhận xét')),
                ('is_verified_purchase', models.BooleanField(default=True, verbose_name='Đã mua hàng thực tế')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Số lượt thích hữu ích')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='Sản phẩm')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Đánh giá sản phẩm',
                'verbose_name_plural': 'Danh sách Đánh giá sản phẩm',
                'db_table': 'product_reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
