# Generated by Django 6.1.1 on 2026-09-11 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Mã giao dịch')),
                ('gateway', models.CharField(choices=[('VNPAY', 'VNPay Sandbox'), ('VIETQR', 'VietQR Ngân hàng'), ('WALLET', 'Ví điểm EcoPay'), ('COD', 'Tiền mặt khi nhận')], default='VNPAY', max_length=20, verbose_name='Cổng thanh toán')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số tiền (VNĐ)')),
                ('status', models.CharField(choices=[('PENDING', 'Đang xử lý'), ('SUCCESS', 'Thành công'), ('FAILED', 'Thất bại')], db_index=True, default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('vnp_transaction_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã GD VNPay')),
                ('vnp_bank_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ngân hàng thanh toán')),
                ('vnp_card_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Loại thẻ')),
                ('response_data', models.JSONField(blank=True, null=True, verbose_name='Dữ liệu phản hồi gốc')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Giao dịch thanh toán',
                'verbose_name_plural': 'Danh sách Giao dịch thanh toán',
                'db_table': 'payment_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
