# Generated by Django 6.1.1 on 2026-09-11 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, default='bi-basket', max_length=100, null=True, verbose_name='Icon Bootstrap')),
                ('image', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ảnh danh mục')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Đang hoạt động')),
                ('display_order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
            ],
            options={
                'verbose_name': 'Danh mục hoa quả',
                'verbose_name_plural': 'Danh mục hoa quả',
                'db_table': 'categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Tên sản phẩm')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='Slug URL SEO')),
                ('sku', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Mã SKU')),
                ('price', models.DecimalField(db_index=True, decimal_places=0, max_digits=12, verbose_name='Giá bán hiện tại (VNĐ)')),
                ('original_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Giá gốc (VNĐ)')),
                ('discount_percent', models.IntegerField(default=0, verbose_name='Phần trăm giảm giá (%)')),
                ('unit', models.CharField(default='kg', max_length=50, verbose_name='Đơn vị tính (kg, hộp, quả, khay)')),
                ('stock', models.PositiveIntegerField(default=100, verbose_name='Số lượng tồn kho')),
                ('season', models.CharField(choices=[('IN_SEASON', 'Đúng mùa vụ (Tươi ngon nhất)'), ('OFF_SEASON', 'Trái mùa (Hàng tuyển chọn cao cấp)'), ('ALL_YEAR', 'Quanh năm')], db_index=True, default='IN_SEASON', max_length=20, verbose_name='Mùa vụ')),
                ('origin', models.CharField(default='Việt Nam', max_length=150, verbose_name='Xuất xứ')),
                ('certification', models.CharField(default='VietGAP / Chuẩn Organic', max_length=150, verbose_name='Tiêu chuẩn chứng nhận')),
                ('calories', models.CharField(blank=True, default='52 kcal / 100g', max_length=100, null=True, verbose_name='Hàm lượng calo')),
                ('vitamins', models.CharField(blank=True, default='Vitamin C, A, Chất xơ', max_length=255, null=True, verbose_name='Hàm lượng vitamin')),
                ('storage_guide', models.TextField(blank=True, default='Bảo quản ngăn mát tủ lạnh 4-8 độ C', null=True, verbose_name='Hướng dẫn bảo quản')),
                ('shelf_life', models.CharField(blank=True, default='5 - 7 ngày trong tủ lạnh', max_length=100, null=True, verbose_name='Hạn sử dụng')),
                ('short_description', models.CharField(max_length=500, verbose_name='Mô tả ngắn')),
                ('description', models.TextField(verbose_name='Mô tả chi tiết sản phẩm')),
                ('image', models.CharField(max_length=500, verbose_name='Ảnh đại diện chính')),
                ('tags', models.CharField(blank=True, help_text='Phân tách bằng dấu phẩy', max_length=255, null=True, verbose_name='Tags tìm kiếm')),
                ('rating', models.DecimalField(db_index=True, decimal_places=1, default=5.0, max_digits=3, verbose_name='Điểm đánh giá')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='Số lượt đánh giá')),
                ('sold_count', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Đã bán')),
                ('is_available', models.BooleanField(db_index=True, default=True, verbose_name='Còn hàng kinh doanh')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='Sản phẩm nổi bật')),
                ('is_bestseller', models.BooleanField(db_index=True, default=False, verbose_name='Sản phẩm bán chạy')),
                ('is_organic', models.BooleanField(default=True, verbose_name='Hữu cơ chuẩn sạch')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title SEO')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description SEO')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Sản phẩm hoa quả',
                'verbose_name_plural': 'Danh sách Sản phẩm',
                'db_table': 'products',
                'ordering': ['-is_featured', '-sold_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.CharField(max_length=500, verbose_name='Đường dẫn ảnh')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Thẻ alt ảnh (SEO)')),
                ('display_order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='products.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Ảnh sản phẩm',
                'verbose_name_plural': 'Thư viện ảnh sản phẩm',
                'db_table': 'product_images',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
